New log file opened at Tue Sep 29 10:35:26 CEST 2015 by 3564@Toshiba-Robin
Taking next connection to: 49416
New client attempting to connect on port: 49417-49416
  Address = /192.168.178.32:49416
This client on port 49417 has uuid 5a662096-0a53-40ed-bded-6da4edba7370 configName activator humanReadableName Activator protocolVersion 3 featureTags Vector()
Connected Clients: activator-5a662096-0a53-40ed-bded-6da4edba7370
Taking next connection to: 49416
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 49416
New client attempting to connect on port: 49444-49416
  Address = /192.168.178.32:49416
Handshake exception on socket: 49444
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at java.io.DataInputStream.readInt(Unknown Source)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 49416
New client attempting to connect on port: 49445-49416
  Address = /192.168.178.32:49416
This client on port 49445 has uuid 1317535b-066f-4dd1-9933-cd490c15b0bb configName play-fork-run humanReadableName Play Fork Run protocolVersion 1 featureTags Vector()
Connected Clients: activator-5a662096-0a53-40ed-bded-6da4edba7370, play-fork-run-1317535b-066f-4dd1-9933-cd490c15b0bb
Taking next connection to: 49416
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 49416
New client attempting to connect on port: 49503-49416
  Address = /192.168.178.32:49416
Handshake exception on socket: 49503
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at java.io.DataInputStream.readInt(Unknown Source)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 49416
New client attempting to connect on port: 49504-49416
  Address = /192.168.178.32:49416
This client on port 49504 has uuid 52de2456-50af-4978-8bf5-b3f0ff483e1c configName play-fork-run humanReadableName Play Fork Run protocolVersion 1 featureTags Vector()
Connected Clients: activator-5a662096-0a53-40ed-bded-6da4edba7370, play-fork-run-52de2456-50af-4978-8bf5-b3f0ff483e1c
Taking next connection to: 49416
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 49416
New client attempting to connect on port: 49539-49416
  Address = /192.168.178.32:49416
Handshake exception on socket: 49539
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readInt(Unknown Source)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 49416
New client attempting to connect on port: 49540-49416
  Address = /192.168.178.32:49416
This client on port 49540 has uuid 1e85dc29-5e27-4781-961d-3ad881f2fddf configName play-fork-run humanReadableName Play Fork Run protocolVersion 1 featureTags Vector()
Connected Clients: activator-5a662096-0a53-40ed-bded-6da4edba7370, play-fork-run-1e85dc29-5e27-4781-961d-3ad881f2fddf
Taking next connection to: 49416
New client attempting to connect on port: 49595-49416
  Address = /192.168.178.32:49416
Handshake exception on socket: 49595
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at java.io.DataInputStream.readInt(Unknown Source)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 49416
New client attempting to connect on port: 49596-49416
  Address = /192.168.178.32:49416
This client on port 49596 has uuid 576cb3fc-df31-4578-aab1-b55fc0fe891e configName play-fork-run humanReadableName Play Fork Run protocolVersion 1 featureTags Vector()
Connected Clients: activator-5a662096-0a53-40ed-bded-6da4edba7370, play-fork-run-576cb3fc-df31-4578-aab1-b55fc0fe891e
Taking next connection to: 49416
